# Generated by Django 2.2.4 on 2021-07-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_stock',
            new_name='is_onSale',
        ),
    ]
