# Generated by Django 2.2.4 on 2021-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0002_auto_20210715_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='is_onSale',
            field=models.BooleanField(default=False),
        ),
    ]
