# Generated by Django 2.2.4 on 2021-07-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0003_auto_20210725_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
    ]
