# Generated by Django 2.2.4 on 2021-07-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0003_auto_20210707_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
