# Generated by Django 2.2.4 on 2021-07-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0004_auto_20210725_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='name',
        ),
    ]
