# Generated by Django 2.2.4 on 2021-06-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0004_auto_20210620_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
