# Generated by Django 2.2.4 on 2021-07-08 00:38

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0004_auto_20210707_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
