# Generated by Django 2.2.4 on 2021-06-26 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0005_auto_20210625_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='phot2',
            new_name='phot02',
        ),
    ]
