# Generated by Django 2.2.4 on 2021-06-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0005_remove_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tshirt', models.IntegerField(default='1', editable=False, max_length='2')),
                ('tanktop', models.IntegerField(default='2', editable=False, max_length='2')),
                ('longsleeve', models.IntegerField(default='3', editable=False, max_length='2')),
                ('sweater', models.IntegerField(default='4', editable=False, max_length='2')),
                ('hoodie', models.IntegerField(default='5', editable=False, max_length='2')),
                ('jacket', models.IntegerField(default='6', editable=False, max_length='2')),
                ('coat', models.IntegerField(default='7', editable=False, max_length='2')),
                ('caridan', models.IntegerField(default='8', editable=False, max_length='2')),
                ('buttonup', models.IntegerField(default='9', editable=False, max_length='2')),
                ('hat', models.IntegerField(default='10', editable=False, max_length='2')),
                ('shoes', models.IntegerField(default='11', editable=False, max_length='2')),
                ('jeans', models.IntegerField(default='12', editable=False, max_length='2')),
                ('khakis', models.IntegerField(default='13', editable=False, max_length='2')),
                ('shorts', models.IntegerField(default='14', editable=False, max_length='2')),
                ('socks', models.IntegerField(default='15', editable=False, max_length='2')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='products/')),
                ('phot2', models.ImageField(null=True, upload_to='products/')),
                ('photo3', models.ImageField(null=True, upload_to='products/')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StoreApp.Categories')),
            ],
        ),
    ]
