# Generated by Django 2.2.4 on 2021-06-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0006_categories_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='phot2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo3',
        ),
    ]
