# Generated by Django 2.2.4 on 2021-08-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0008_auto_20210802_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
    ]
