# Generated by Django 2.2.4 on 2021-08-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0009_remove_wishlist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
